# Generated by Django 5.2.2 on 2025-06-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0002_alter_reseña_usuario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('libros', models.ManyToManyField(blank=True, to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
            ],
        ),
    ]
