# Generated by Django 5.2.2 on 2025-06-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_reseña_usuario'),
        ('ventas', '0004_pedido_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='libros',
            field=models.ManyToManyField(blank=True, to='libros.libro'),
        ),
    ]
