# Generated by Django 5.2.2 on 2025-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_reseña_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='generico', max_length=50),
        ),
    ]
